version: '3.1'
services:
  db:
    image: mysql
    container_name: imbmary
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
    ports:
      - "3306:3306"
    volumes:
      - imbmary_data:/var/lib/mysql

volumes:
  imbmary_data:
